"""empty message

Revision ID: 1622189657245
Revises: 1622188710419
Create Date: 2021-05-28 15:14:17.621880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1622189657245'
down_revision = '1622188710419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user-weekly-review', 'review',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user-weekly-review', 'review',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
