"""empty message

Revision ID: 1622232825616
Revises: 1622232207354
Create Date: 2021-05-29 03:13:46.133483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1622232825616'
down_revision = '1622232207354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backlog', sa.Column('iteration_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'backlog', 'iteration', ['iteration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'backlog', type_='foreignkey')
    op.drop_column('backlog', 'iteration_id')
    # ### end Alembic commands ###
