"""empty message

Revision ID: 1625742891830
Revises: 1625736539894
Create Date: 2021-07-08 18:14:52.393582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1625742891830'
down_revision = '1625736539894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'job_title')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('job_title', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
